/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.Controlador_consultar;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author William Diaz
 */
public class Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Consultas
     */
    public Consultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Button_buscarCorreo = new javax.swing.JButton();
        Button_buscarApellido = new javax.swing.JButton();
        Button_programa = new javax.swing.JButton();
        Button_cantidadPrograma = new javax.swing.JButton();
        Button_fecha = new javax.swing.JButton();
        Button_buscarCelular = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        campo_apellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Button_regresar = new javax.swing.JButton();
        campo_programa = new javax.swing.JTextField();
        campo_programa_cantidad = new javax.swing.JTextField();
        campo_correo = new javax.swing.JTextField();
        campo_fecha = new javax.swing.JTextField();
        campo_celular = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        respuestas = new javax.swing.JTextArea();
        button_otraConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(44, 10, 94));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Consultas");

        Button_buscarCorreo.setBackground(new java.awt.Color(204, 195, 11));
        Button_buscarCorreo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Button_buscarCorreo.setText("Buscar estudiante por correo electronico");
        Button_buscarCorreo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button_buscarCorreo.setBorderPainted(false);
        Button_buscarCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Button_buscarCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_buscarCorreoActionPerformed(evt);
            }
        });

        Button_buscarApellido.setBackground(new java.awt.Color(204, 195, 11));
        Button_buscarApellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Button_buscarApellido.setText("Buscar estudiante por apellidos");
        Button_buscarApellido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button_buscarApellido.setBorderPainted(false);
        Button_buscarApellido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Button_buscarApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_buscarApellidoActionPerformed(evt);
            }
        });

        Button_programa.setBackground(new java.awt.Color(204, 195, 11));
        Button_programa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Button_programa.setText("Buscar por programa");
        Button_programa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button_programa.setBorderPainted(false);
        Button_programa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Button_programa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_programaActionPerformed(evt);
            }
        });

        Button_cantidadPrograma.setBackground(new java.awt.Color(204, 195, 11));
        Button_cantidadPrograma.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Button_cantidadPrograma.setText("Buscar cantidad de estudiantes por programa");
        Button_cantidadPrograma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button_cantidadPrograma.setBorderPainted(false);
        Button_cantidadPrograma.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Button_cantidadPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_cantidadProgramaActionPerformed(evt);
            }
        });

        Button_fecha.setBackground(new java.awt.Color(204, 195, 11));
        Button_fecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Button_fecha.setText("Buscar por fecha de nacimiento");
        Button_fecha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button_fecha.setBorderPainted(false);
        Button_fecha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Button_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_fechaActionPerformed(evt);
            }
        });

        Button_buscarCelular.setBackground(new java.awt.Color(204, 195, 11));
        Button_buscarCelular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Button_buscarCelular.setText("Buscar por numero de celular");
        Button_buscarCelular.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button_buscarCelular.setBorderPainted(false);
        Button_buscarCelular.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Button_buscarCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_buscarCelularActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Ingresar datos ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Datos consultados");

        Button_regresar.setBackground(new java.awt.Color(77, 148, 223));
        Button_regresar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Button_regresar.setText("REGRESAR AL MENU");
        Button_regresar.setBorderPainted(false);
        Button_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_regresarActionPerformed(evt);
            }
        });

        respuestas.setEditable(false);
        respuestas.setColumns(20);
        respuestas.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        respuestas.setRows(1);
        respuestas.setToolTipText("");
        jScrollPane1.setViewportView(respuestas);

        button_otraConsulta.setBackground(new java.awt.Color(77, 148, 223));
        button_otraConsulta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button_otraConsulta.setText("REALIZAR OTRA CONSULTA");
        button_otraConsulta.setBorderPainted(false);
        button_otraConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_otraConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel2)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(campo_programa, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(Button_programa, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campo_correo, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                    .addComponent(campo_apellidos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button_buscarApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button_buscarCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campo_fecha)
                                    .addComponent(campo_programa_cantidad)
                                    .addComponent(campo_celular, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Button_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                    .addComponent(Button_buscarCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                    .addComponent(Button_cantidadPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(284, 284, 284))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(button_otraConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_regresar)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_buscarCorreo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(campo_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_buscarApellido)
                    .addComponent(campo_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_programa)
                    .addComponent(campo_programa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_cantidadPrograma)
                    .addComponent(campo_programa_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Button_fecha)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campo_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Button_buscarCelular)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campo_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_regresar)
                    .addComponent(button_otraConsulta))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_buscarCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_buscarCelularActionPerformed
        Controlador_consultar.buscar_celular();
    }//GEN-LAST:event_Button_buscarCelularActionPerformed

    private void Button_buscarCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_buscarCorreoActionPerformed
        Controlador_consultar.buscar_correo_electronico();
    }//GEN-LAST:event_Button_buscarCorreoActionPerformed

    private void Button_buscarApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_buscarApellidoActionPerformed
        Controlador_consultar.buscar_apellidos();
    }//GEN-LAST:event_Button_buscarApellidoActionPerformed

    private void Button_programaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_programaActionPerformed
        Controlador_consultar.buscar_programa();
    }//GEN-LAST:event_Button_programaActionPerformed

    private void Button_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_fechaActionPerformed
        Controlador_consultar.buscar_fecha_nacimiento();
    }//GEN-LAST:event_Button_fechaActionPerformed

    private void Button_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_regresarActionPerformed
        Controlador_consultar.regresar();
    }//GEN-LAST:event_Button_regresarActionPerformed

    private void Button_cantidadProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_cantidadProgramaActionPerformed
        Controlador_consultar.buscar_programa_cantidad();
    }//GEN-LAST:event_Button_cantidadProgramaActionPerformed

    private void button_otraConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_otraConsultaActionPerformed
        Controlador_consultar.otra_busqueda();
    }//GEN-LAST:event_button_otraConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }

    public JTextField getCampo_apellidos() {
        return campo_apellidos;
    }

    public JTextField getCampo_celular() {
        return campo_celular;
    }

    public JTextField getCampo_correo() {
        return campo_correo;
    }

    public JTextField getCampo_fecha() {
        return campo_fecha;
    }

    public JTextField getCampo_programa() {
        return campo_programa;
    }

    public JTextField getCampo_programa_cantidad() {
        return campo_programa_cantidad;
    }

    public JTextArea getRespuestas() {
        return respuestas;
    }

   


    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_buscarApellido;
    private javax.swing.JButton Button_buscarCelular;
    private javax.swing.JButton Button_buscarCorreo;
    private javax.swing.JButton Button_cantidadPrograma;
    private javax.swing.JButton Button_fecha;
    private javax.swing.JButton Button_programa;
    private javax.swing.JButton Button_regresar;
    private javax.swing.JButton button_otraConsulta;
    private javax.swing.JTextField campo_apellidos;
    private javax.swing.JTextField campo_celular;
    private javax.swing.JTextField campo_correo;
    private javax.swing.JTextField campo_fecha;
    private javax.swing.JTextField campo_programa;
    private javax.swing.JTextField campo_programa_cantidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea respuestas;
    // End of variables declaration//GEN-END:variables
}
