
package vistas;

import controladores.Controlador_ingresar;
import javax.swing.JTextField;
import modelos.Alumno;
import DAOS_JDBC.SQLDaoManager;


public class Ingresar_estudiante extends javax.swing.JFrame {
    Controlador_ingresar objcontroladoringresar=new Controlador_ingresar();
            
    public Ingresar_estudiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_titulo = new javax.swing.JLabel();
        label_nombres = new javax.swing.JLabel();
        Label_apellidos = new javax.swing.JLabel();
        Label_fecha = new javax.swing.JLabel();
        Label_correoinst = new javax.swing.JLabel();
        Label_correoperso = new javax.swing.JLabel();
        Label_numeroCelular = new javax.swing.JLabel();
        Label_numerofijo = new javax.swing.JLabel();
        Label_programa = new javax.swing.JLabel();
        campo_nombres = new javax.swing.JTextField();
        campo_apellidos = new javax.swing.JTextField();
        campo_fechanacimiento = new javax.swing.JTextField();
        campo_correoinst = new javax.swing.JTextField();
        campo_correoperso = new javax.swing.JTextField();
        campo_numcelular = new javax.swing.JTextField();
        campo_numfijo = new javax.swing.JTextField();
        campo_programa = new javax.swing.JTextField();
        button_crear = new javax.swing.JButton();
        campo_respuesta = new javax.swing.JTextField();
        button_regresar = new javax.swing.JButton();
        Button_crearNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_titulo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Label_titulo.setText("INGRESAR ESTUDIANTES");

        label_nombres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_nombres.setText("Nombres:");

        Label_apellidos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label_apellidos.setText("Apellidos:");

        Label_fecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label_fecha.setText("Fecha de nacimiento:");

        Label_correoinst.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label_correoinst.setText("Correo institucional:");

        Label_correoperso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label_correoperso.setText("Correo personal:");

        Label_numeroCelular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label_numeroCelular.setText("Numero de celular:");

        Label_numerofijo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label_numerofijo.setText("Numero fijo:");

        Label_programa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label_programa.setText("Programa:");

        button_crear.setBackground(new java.awt.Color(238, 124, 11));
        button_crear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button_crear.setText("CREAR");
        button_crear.setBorderPainted(false);
        button_crear.setFocusPainted(false);
        button_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_crearActionPerformed(evt);
            }
        });

        button_regresar.setBackground(new java.awt.Color(77, 148, 223));
        button_regresar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button_regresar.setText("REGRESAR AL MENU");
        button_regresar.setBorderPainted(false);
        button_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_regresarActionPerformed(evt);
            }
        });

        Button_crearNuevo.setBackground(new java.awt.Color(77, 148, 223));
        Button_crearNuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Button_crearNuevo.setText("CREAR OTRO USUARIO");
        Button_crearNuevo.setBorderPainted(false);
        Button_crearNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_crearNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Label_correoinst)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(campo_correoinst))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Label_fecha)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(campo_fechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Label_correoperso)
                                    .addGap(18, 18, 18)
                                    .addComponent(campo_correoperso))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Label_numeroCelular)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(campo_numcelular))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(label_nombres)
                                    .addGap(18, 18, 18)
                                    .addComponent(campo_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Label_numerofijo)
                                        .addComponent(Label_programa))
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(campo_numfijo)
                                        .addComponent(campo_programa))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label_apellidos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campo_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(Label_titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(button_crear))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(campo_respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Button_crearNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_regresar)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Label_titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nombres)
                            .addComponent(campo_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_apellidos)
                            .addComponent(campo_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_fecha)
                            .addComponent(campo_fechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_correoinst)
                            .addComponent(campo_correoinst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_correoperso)
                            .addComponent(campo_correoperso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_numeroCelular)
                            .addComponent(campo_numcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Label_numerofijo))
                    .addComponent(campo_numfijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_programa)
                    .addComponent(campo_programa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_crear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_crearNuevo)
                    .addComponent(button_regresar))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_crearActionPerformed

        Controlador_ingresar.crear();
    }//GEN-LAST:event_button_crearActionPerformed

    private void button_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_regresarActionPerformed
        Controlador_ingresar.regresar();
    }//GEN-LAST:event_button_regresarActionPerformed

    private void Button_crearNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_crearNuevoActionPerformed
        Controlador_ingresar.limpiar();
    }//GEN-LAST:event_Button_crearNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingresar_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingresar_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingresar_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingresar_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingresar_estudiante().setVisible(true);
            }
        });
    }

    public JTextField getCampo_apellidos() {
        return campo_apellidos;
    }

    public JTextField getCampo_correoinst() {
        return campo_correoinst;
    }

    public JTextField getCampo_correoperso() {
        return campo_correoperso;
    }

    public JTextField getCampo_fechanacimiento() {
        return campo_fechanacimiento;
    }

    public JTextField getCampo_nombres() {
        return campo_nombres;
    }

    public JTextField getCampo_numcelular() {
        return campo_numcelular;
    }

    public JTextField getCampo_numfijo() {
        return campo_numfijo;
    }

    public JTextField getCampo_programa() {
        return campo_programa;
    }

    public JTextField getCampo_respuesta() {
        return campo_respuesta;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_crearNuevo;
    private javax.swing.JLabel Label_apellidos;
    private javax.swing.JLabel Label_correoinst;
    private javax.swing.JLabel Label_correoperso;
    private javax.swing.JLabel Label_fecha;
    private javax.swing.JLabel Label_numeroCelular;
    private javax.swing.JLabel Label_numerofijo;
    private javax.swing.JLabel Label_programa;
    private javax.swing.JLabel Label_titulo;
    private javax.swing.JButton button_crear;
    private javax.swing.JButton button_regresar;
    private javax.swing.JTextField campo_apellidos;
    private javax.swing.JTextField campo_correoinst;
    private javax.swing.JTextField campo_correoperso;
    private javax.swing.JTextField campo_fechanacimiento;
    private javax.swing.JTextField campo_nombres;
    private javax.swing.JTextField campo_numcelular;
    private javax.swing.JTextField campo_numfijo;
    private javax.swing.JTextField campo_programa;
    private javax.swing.JTextField campo_respuesta;
    private javax.swing.JLabel label_nombres;
    // End of variables declaration//GEN-END:variables

}
